### ISSUE TITLE
Can I please join the organization

### ISSUE THREAD

**Issue by MrPigeontheCoder** [windows93-community/DOM42#1]
I want to help make win93 apps and stuff

**Comment by stretch07** [comment]
@MrPigeontheCoder let me know if you want to join @win93-community

**Comment by MrPigeontheCoder** [comment]
@its-pablo I do want to join. I have quite a bit of knowledge about win93 and the syntax and some javascript.

**Comment by stretch07** [comment]
@MrPigeontheCoder awesome! I'll send you an invitation

**Comment by MrPigeontheCoder** [comment]
> @MrPigeontheCoder awesome! I'll send you an invitation

That's odd. You sent me an invite to a different organisation... BUT! I'll accept it because it's somewhat more active

**Comment by stretch07** [comment]
> > @MrPigeontheCoder awesome! I'll send you an invitation
> 
> That's odd. You sent me an invite to a different organisation... BUT! I'll accept it because it's somewhat more active

Yes! That is what i meant. The new org is more active than this one

**Comment by MrPigeontheCoder** [comment]
> > > @MrPigeontheCoder awesome! I'll send you an invitation
> > 
> > That's odd. You sent me an invite to a different organisation... BUT! I'll accept it because it's somewhat more active
> 
> Yes! That is what i meant. The new org is more active than this one

Ok, thanks! It's currently night-time for me, so I'll get working on win93 stuff tomorrow in the afternoon...

**Comment by stretch07** [comment]
Ah ok, no worries!

**Comment by MrPigeontheCoder** [comment]
stale

**Comment by MrPigeontheCoder** [comment]
stale
